[package]
name = "kgame-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pancurses = "0.17"
pdcurses-sys = "0.7"
#ncurses-rs = "0.0.3"